/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author PUESTO-A1
 */
public class friAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form friAlumnos
     */
    public friAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbApellido = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbDni = new javax.swing.JLabel();
        lbFechaNacimiento = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        tfFechaNacimiento = new javax.swing.JFormattedTextField();
        ckEstado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setForeground(new java.awt.Color(173, 186, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbApellido.setForeground(new java.awt.Color(173, 186, 199));
        lbApellido.setText("Apellido");
        jPanel1.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 30));

        lbNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(173, 186, 199));
        lbNombre.setText("Nombre");
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 30));

        lbDni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbDni.setForeground(new java.awt.Color(173, 186, 199));
        lbDni.setText("DNI");
        jPanel1.add(lbDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 30));

        lbFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbFechaNacimiento.setForeground(new java.awt.Color(173, 186, 199));
        lbFechaNacimiento.setText("Fecha de Nacimiento");
        jPanel1.add(lbFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 30));

        lbEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(173, 186, 199));
        lbEstado.setText("Estado");
        jPanel1.add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 30));

        tfApellido.setBackground(new java.awt.Color(34, 39, 46));
        tfApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfApellido.setForeground(new java.awt.Color(173, 186, 199));
        tfApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(173, 186, 199)));
        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 30));

        tfNombre.setBackground(new java.awt.Color(34, 39, 46));
        tfNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(173, 186, 199));
        tfNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(173, 186, 199)));
        jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 200, 30));

        tfDni.setBackground(new java.awt.Color(34, 39, 46));
        tfDni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDni.setForeground(new java.awt.Color(173, 186, 199));
        tfDni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(173, 186, 199)));
        jPanel1.add(tfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 200, 30));

        tfFechaNacimiento.setBackground(new java.awt.Color(34, 39, 46));
        tfFechaNacimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(173, 186, 199)));
        tfFechaNacimiento.setForeground(new java.awt.Color(173, 186, 199));
        tfFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        tfFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tfFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, 30));

        ckEstado.setBackground(new java.awt.Color(34, 39, 46));
        ckEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ckEstado.setForeground(new java.awt.Color(173, 186, 199));
        ckEstado.setText("Activo");
        ckEstado.setContentAreaFilled(false);
        ckEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(ckEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 200, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 186, 199));
        jLabel1.setText("Formulario de alumno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btGuardar.setBackground(new java.awt.Color(34, 39, 46));
        btGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(173, 186, 199));
        btGuardar.setText("Guardar");
        btGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 186, 199), 1, true));
        btGuardar.setContentAreaFilled(false);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 100, 30));

        btSalir.setBackground(new java.awt.Color(34, 39, 46));
        btSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalir.setForeground(new java.awt.Color(173, 186, 199));
        btSalir.setText("Salir");
        btSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 186, 199), 1, true));
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void ckEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckEstadoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.JCheckBox ckEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFechaNacimiento;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDni;
    private javax.swing.JFormattedTextField tfFechaNacimiento;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
