/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AlumnoData;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author maxim
 */
public class friNotas extends javax.swing.JInternalFrame {

    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private ArrayList<Materia> materias;
    private InscripcionData inscripcionData;
    private DefaultTableModel modelo;
    private InscripcionData insData;
    
    private final Materia m = new Materia();
    /**
     * Creates new form friNotas
     */
    public friNotas() {
        initComponents();
        modelo= new DefaultTableModel();
        materiaData= new MateriaData();
        materias= new ArrayList();
        materias=(ArrayList) materiaData.listarMaterias();
        cargarCombo();
        cabecera();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo1 = new javax.swing.JLabel();
        lbMateria = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaterias = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(173, 186, 199));
        lbTitulo1.setText("Formulario de notas");
        jPanel1.add(lbTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lbMateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMateria.setForeground(new java.awt.Color(173, 186, 199));
        lbMateria.setText("Materia");
        jPanel1.add(lbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 30));

        cbMaterias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbMaterias.setForeground(new java.awt.Color(173, 186, 199));
        jPanel1.add(cbMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 390, 30));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(720, 402));

        tbMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 700, 280));

        btnSalir.setBackground(new java.awt.Color(34, 39, 46));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(173, 186, 199));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 431, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Materia> cbMaterias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JTable tbMaterias;
    // End of variables declaration//GEN-END:variables
    
    private void cargarCombo() {
        cbMaterias.addItem(null);
        materias=(ArrayList) materiaData.listarMaterias();
        for (Materia materia : materias) {
            cbMaterias.addItem(materia);
            
        }
    }

    private void cabecera() {
       ArrayList<Object> columnas= new ArrayList();
       columnas.add("ID");
       columnas.add("Nombre");
       columnas.add("Apellido");
       columnas.add("DNI");
       columnas.add("Fecha de nacimiento");
        for (Object ob : columnas) {
            modelo.addColumn(ob);
            
        }
        tbMaterias.setModel(modelo);
    }

    private void cargarTabla() {
       borrarFilasTabla();
       Materia selec= new Materia();
       selec= (Materia) cbMaterias.getSelectedItem();
       if(selec!=null){
       ArrayList <Inscripcion> ins= new ArrayList();
       ins= (ArrayList)insData.obtenerAlumnosInscriptos(selec);
       if(ins.isEmpty()){
           JOptionPane.showMessageDialog(this, "No hay inscriptos en esta materia");
       }
       for (Inscripcion in : ins) {
            modelo.addRow(new Object[]{in.getAlumno().getIdAlumno(),
            in.getAlumno().getNombre(),
            in.getAlumno().getApellido(),
            in.getAlumno().getDni(),
            in.getAlumno().getFechaNacimiento()});
        }
       tbMaterias.setModel(modelo);
      
    }
    }
    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }
    }

}
