/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AlumnoData;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author maxim
 */
public class friNotas extends javax.swing.JInternalFrame {

    private ArrayList<Materia> materias;
    private DefaultTableModel modelo;
    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private InscripcionData inscripcionData;

    private final Materia m = new Materia();

    /**
     * Creates new form friNotas
     */
    public friNotas() {
        initComponents();
        modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 0 || column == 1 || column == 2 ){
                    return false;
                } else{
                    return true;
                }
            }
        };
        alumnoData = new AlumnoData();
        materiaData = new MateriaData();
        inscripcionData = new InscripcionData();
        materias = new ArrayList();
        materias = (ArrayList) materiaData.listarMaterias();
        cargarCombo();
        cabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo1 = new javax.swing.JLabel();
        lbMateria = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaterias = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(173, 186, 199));
        lbTitulo1.setText("Formulario de notas");
        jPanel1.add(lbTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lbMateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMateria.setForeground(new java.awt.Color(173, 186, 199));
        lbMateria.setText("Materia");
        jPanel1.add(lbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 30));

        cbMaterias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbMaterias.setForeground(new java.awt.Color(173, 186, 199));
        cbMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriasActionPerformed(evt);
            }
        });
        jPanel1.add(cbMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 390, 30));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(720, 402));

        tbMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 700, 280));

        btnGuardar.setBackground(new java.awt.Color(34, 39, 46));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(173, 186, 199));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 110, 30));

        btnSalir1.setBackground(new java.awt.Color(34, 39, 46));
        btnSalir1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(173, 186, 199));
        btnSalir1.setText("Salir");
        btnSalir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir1.setContentAreaFilled(false);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 431, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try{
            int fila = tbMaterias.getSelectedRow();
            if (fila != -1) {
                Float nota = Float.parseFloat((String) modelo.getValueAt(fila, 3));
                if(nota < 0 || nota > 10 || nota.isNaN()){
                    JOptionPane.showMessageDialog(this, "La nota ingresada no es válida.");
                } else {
                    String dniAlumno = (String) modelo.getValueAt(fila, 2);
                    Alumno alu = alumnoData.obtenerAlumnoXDni(dniAlumno);
                    Materia mat = (Materia) cbMaterias.getSelectedItem();
                    inscripcionData.actualizarNota(alu, mat, nota);
                    cargarTabla();
                }
            } else {
                JOptionPane.showMessageDialog(this, "No hay alumno seleccionado.");
            }            
        } catch(ClassCastException e){
            JOptionPane.showMessageDialog(this, "La nota ingresada no es válida.");
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La nota ingresada no es válida.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriasActionPerformed
        cargarTabla();
    }//GEN-LAST:event_cbMateriasActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<Materia> cbMaterias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JTable tbMaterias;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        cbMaterias.addItem(null);
        materias = (ArrayList) materiaData.listarMaterias();
        for (Materia materia : materias) {
            cbMaterias.addItem(materia);
        }
    }

    private void cabecera() {
        ArrayList<Object> columnas = new ArrayList();
        //columnas.add("ID");
        columnas.add("Nombre");
        columnas.add("Apellido");
        columnas.add("DNI");
        columnas.add("Nota");
        for (Object ob : columnas) {
            modelo.addColumn(ob);
        }
        tbMaterias.setModel(modelo);
    }

    private void cargarTabla() {
        borrarFilasTabla();
        Materia materia;
        ArrayList<Inscripcion> inscripciones;
        materia = (Materia) cbMaterias.getSelectedItem();
        if (materia != null) {
            inscripciones = (ArrayList) inscripcionData.obtenerAlumnosInscriptos(materia);
            if (inscripciones.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay inscriptos en esta materia.");
            }
            for (Inscripcion in : inscripciones) {
                modelo.addRow(new Object[]{
                    //in.getAlumno().getIdAlumno(),
                    in.getAlumno().getNombre(),
                    in.getAlumno().getApellido(),
                    in.getAlumno().getDni(),
                    in.getNotaFinal()
                });
            }
            tbMaterias.setModel(modelo);
        }
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;
            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }
    }

}
