/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JDesktopPane;



/**
 *
 * @author PUESTO-A1
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jmAlumno = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();
        jmMateria = new javax.swing.JMenuItem();
        jMInscripciones = new javax.swing.JMenu();
        jMIInscripciones = new javax.swing.JMenuItem();
        jMCargarNotas = new javax.swing.JMenu();
        jMICargarNotas = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        dpPrincipal.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jMAlumnos.setText("Universidad");
        jMAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnosActionPerformed(evt);
            }
        });

        jmAlumno.setText("Alumno");
        jmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnoActionPerformed(evt);
            }
        });
        jMAlumnos.add(jmAlumno);

        jMenuBar1.add(jMAlumnos);

        mnSalir.setText("Materias");

        jmMateria.setText("Materia");
        jmMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriaActionPerformed(evt);
            }
        });
        mnSalir.add(jmMateria);

        jMenuBar1.add(mnSalir);

        jMInscripciones.setText("Inscripciones");

        jMIInscripciones.setText("Formulario de Inscripciones");
        jMIInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInscripcionesActionPerformed(evt);
            }
        });
        jMInscripciones.add(jMIInscripciones);

        jMenuBar1.add(jMInscripciones);

        jMCargarNotas.setText("Notas");

        jMICargarNotas.setText("Cargar Notas");
        jMCargarNotas.add(jMICargarNotas);

        jMenuBar1.add(jMCargarNotas);

        jMConsultas.setText("Consultas");

        jMenuItem1.setText("Consultar alumnos por materia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMConsultas.add(jMenuItem1);

        jMenuBar1.add(jMConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMAlumnosActionPerformed

    private void jmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnoActionPerformed
        dpPrincipal.removeAll();
        dpPrincipal.repaint();
        friAlumnos ventAlumno= new friAlumnos();
       dpPrincipal.add(ventAlumno);
       ventAlumno.setVisible(true);
    }//GEN-LAST:event_jmAlumnoActionPerformed

    private void jmMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriaActionPerformed
        dpPrincipal.removeAll();
        dpPrincipal.repaint();
        friMaterias ventMateria= new friMaterias();
        dpPrincipal.add(ventMateria);
        ventMateria.setVisible(true);
    }//GEN-LAST:event_jmMateriaActionPerformed

    private void jMIInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInscripcionesActionPerformed
        dpPrincipal.removeAll();
        dpPrincipal.repaint();
        friInscripciones ventInsc= new friInscripciones();
        dpPrincipal.add(ventInsc);
        ventInsc.setVisible(true);
    }//GEN-LAST:event_jMIInscripcionesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dpPrincipal.removeAll();
        dpPrincipal.repaint();
       friConsultas consulta= new friConsultas();
       dpPrincipal.add(consulta);
      consulta.setVisible(true);
   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        friAlumnos vent= new friAlumnos();
        vent.setVisible(true);
        frmPrincipal vent1= new frmPrincipal();
        vent1.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMCargarNotas;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMICargarNotas;
    private javax.swing.JMenuItem jMIInscripciones;
    private javax.swing.JMenu jMInscripciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmAlumno;
    private javax.swing.JMenuItem jmMateria;
    private javax.swing.JMenu mnSalir;
    // End of variables declaration//GEN-END:variables
}
